<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="10.0.1" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Sol.Api.Contracts\Sol.Api.Contracts.csproj" />
    <ProjectReference Include="..\Sol.Domain\Sol.Domain.csproj" />
  </ItemGroup>

</Project>
