<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sol.Api.Contracts\Sol.Api.Contracts.csproj" />
    <ProjectReference Include="..\Sol.Api.Swagger\Sol.Api.Swagger.csproj" />
    <ProjectReference Include="..\Sol.Core\Sol.Core.csproj" />
    <ProjectReference Include="..\Sol.Data\Sol.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>  

</Project>
